// type RawEvents = {
//   userId: number;
//   id: number;
//   title: string;
//   completed: boolean;
// };

type RawEVents = {
  body_acronimo: string;
  body_cabpea: string;
  body_cir: string;
  body_cod_aui_direttrice: string;
  body_cod_aui_elemento: string;
  body_cod_gest_cft: string;
  body_cod_gest_ente: string;
  body_cod_gest_ese: string;
  body_cod_gest_sbcp: string;
  body_cod_gest_utr: string;
  body_cod_gest_zon: string;
  body_cod_sist_sbar:string;
  body_codice1: string;
  body_codice2: string;
  body_comepr: number;
  body_competenza: string;
  body_cond_prioritaria: string;
  body_descrizione: string;
  body_diteea: string;
  body_ente: string;
  body_enteea: string;
  body_eserea: string;
  body_flag_istrtu_valido:number;
  body_flags0:number;
  body_flags1: number;
  body_id_cabp: string;
  body_id_esercizio: number;
  body_id_montante: string;
  body_id_sist: string;
  body_id_utr: string;
  body_idele1: number;
  body_idele2: number;
  body_ist_eve_msec: number;
  body_ist_evento: string;
  body_ist_operatore: string;
  body_ist_rtu: string;
  body_ist_rtu_msec: number;
  body_itrans: string;
  body_matricola: string;
  body_montea: string;
  body_nodo: string;
  body_nome1: string;
  body_nome2: string;
  body_nome_apparato: string;
  body_nome_cp: string;
  body_nome_esercizio: string;
  body_nome_montante_cp: string;
  body_nome_montante_cp_sn: string;
  body_nomeea: string;
  body_num_protocollo: number;
  body_orig: string;
  body_parametri: string;
  body_prog_evento: string;
  body_prot_richiesta: string;
  body_protezioni: string;
  body_sigla_apparato: string;
  body_soggev: number;
  body_tipel1: number;
  body_tipel2: number;
  body_tipo_protocollo: number;
  body_topologyId: string;
  body_topologyType: string;
  body_uop: string;
  header_id_co: string;
  header_timestamp: number;
  header_type: string;
  stb_protocollo_blue_team: string;
  stb_protocollo_cft: string;
  stb_protocollo_data_riferimento:string;
  stb_protocollo_day_prog: number;
  stb_protocollo_e_type: number;
  stb_protocollo_esercizio: string;
  stb_protocollo_event_desc: string;
  stb_protocollo_event_nature: number;
  stb_protocollo_event_param: string;
  stb_protocollo_event_type_id: number;
  stb_protocollo_event_type_orig_id: number;
  stb_protocollo_fix_gid: number;
  stb_protocollo_fix_type: string;
  stb_protocollo_id_manovra: string;
  stb_protocollo_num_param_1: number;
  stb_protocollo_num_param_2: number;
  stb_protocollo_num_param_3: number;
  stb_protocollo_num_param_4: number;
  stb_protocollo_num_param_5: number;
  stb_protocollo_num_param_6: number;
  stb_protocollo_num_param_7: number;
  stb_protocollo_obj_full_id: string;
  stb_protocollo_obj_id: number;
  stb_protocollo_obj_prefix:number;
  stb_protocollo_obj_type: number;
  stb_protocollo_obj_type_desc: string;
  stb_protocollo_search_day_prog: string;
  stb_protocollo_search_time: string;
  stb_protocollo_sql_time: string;
  stb_protocollo_uni_terr: string;
  stb_protocollo_unique_id: number;
  stb_protocollo_user_id: string;
  stb_protocollo_utc_time: number;
  telecontrol_id: string;
};
